### ISSUE TITLE
Style/RaiseArgs does not catch raise with both `new` and message params

### ISSUE THREAD

**Issue by DocX** [rubocop/rubocop#10621] opened 2022-05-11 14:31 UTC
## Expected behavior

```rb
raise MyError.new(data: "mydata"), "some error message"
```

According to the documentaion

> The exploded style works identically, but with the addition that it will also suggest constructing error objects when the exception is passed multiple arguments.

it should be offensive when this configuration is used:

```yaml
Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded
  AllowedCompactTypes: []
```

It should be autocorrected to
```rb
raise MyError.new("some error message", data: "mydata")
```

## Actual behavior

No offense is found

## Steps to reproduce the problem

Run rubocop with this configuration:

```yaml
Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded
  AllowedCompactTypes: []
```

on this code:

```rb
raise MyError.new(data: "mydata"), "some error message"
```

## RuboCop version

```
1.29.0 (using Parser 3.1.2.0, rubocop-ast 1.17.0, running on ruby 3.1.0 x86_64-darwin20)
```

**Comment by koic** [comment] 2022-05-11 15:31
The signature of `raise` is below.

```ruby
raise
raise(string, cause: $!)
raise(exception [, string [, array]], cause: $!)
```

https://ruby-doc.org/core-3.1.0/Kernel.html#method-i-raise

So this issue would be an expected behavior because `raise MyError.new(data: 'mydata'), 'message'` and `raise MyError.new('message', data: 'mydata')` are incompatible.

I'm going to close this issue. Thank you.

**Closed by koic** 2022-05-11 15:31 UTC
