### ISSUE TITLE
An error occurred while Layout/HashAlignment

### ISSUE THREAD

**Issue by kassio** [rubocop/rubocop#9870] opened 2021-06-11 10:09 UTC
## Expected behavior

Not raise any errors
 
## Actual behavior

An error occurred while Layout/HashAlignment cop was inspecting 

```ruby
  subject { described_class.new(:form_name, account, helper, {}) }
```

Mention the following information in the issue report:
1.16.1 (using Parser 3.0.1.1, rubocop-ast 1.7.0, running on ruby 3.0.1 x86_64-darwin20)

## RuboCop version

```
$ rubocop -V
1.16.1 (using Parser 3.0.1.1, rubocop-ast 1.7.0, running on ruby 3.0.1 x86_64-darwin20)
  - rubocop-performance 1.11.3
  - rubocop-rails 2.10.1
  - rubocop-rspec 2.4.0
```

**Comment by koic** [comment] 2021-06-11 10:24
The issue is dup with #9861 and resolved by #9862.

**Closed** 2021-06-11 10:24 UTC
Labels: duplicate
