### ISSUE TITLE
Style/IfInsideElse raises error when parsing appsec comment

### ISSUE THREAD

**Issue by mikescar** [rubocop/rubocop#11806] opened 2023-04-17 04:46 UTC
--------

## Expected behavior

If `rubocop` or `standardrb --fix` encounters a comment beginning with with `# appsec: ...`, nothing should happen.

## Actual behavior

```
$ standardrb --fix -d app/controllers/

An error occurred while Style/IfInsideElse cop was inspecting /Users/mikescar/src/staffing_referrals/app/controllers/join_controller.rb:246:12.
Parser::Source::TreeRewriter detected clobbering
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter.rb:427:in `trigger_policy'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter.rb:414:in `enforce_policy'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:233:in `call'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:233:in `swallow'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:97:in `with'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:124:in `place_in_hierarchy'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:106:in `do_combine'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:117:in `place_in_hierarchy'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:131:in `block in combine_children'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:130:in `each'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:130:in `inject'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:130:in `combine_children'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:221:in `merge'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:104:in `do_combine'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter/action.rb:30:in `combine'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/parser-3.2.2.0/lib/parser/source/tree_rewriter.rb:143:in `merge!'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/base.rb:317:in `apply_correction'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/base.rb:406:in `attempt_correction'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/base.rb:387:in `use_corrector'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/base.rb:381:in `correct'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/base.rb:181:in `add_offense'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/style/if_inside_else.rb:75:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:107:in `public_send'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:107:in `block (2 levels) in trigger_responding_cops'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:106:in `block in trigger_responding_cops'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:105:in `each'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:105:in `trigger_responding_cops'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:69:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:157:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:157:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:155:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:157:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:157:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:157:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_if'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:154:in `on_def'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_def'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:154:in `on_class'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:71:in `on_class'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-ast-1.28.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/commissioner.rb:87:in `investigate'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/team.rb:156:in `investigate_partial'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cop/team.rb:91:in `investigate'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:345:in `block in inspect_file'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:344:in `each'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:344:in `flat_map'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:344:in `inspect_file'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:287:in `block in do_inspection_loop'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:321:in `block in iterate_until_no_changes'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:314:in `loop'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:283:in `do_inspection_loop'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:164:in `block in file_offenses'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:189:in `file_offense_cache'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:163:in `file_offenses'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:154:in `process_file'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:134:in `each'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:134:in `reduce'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:134:in `each_inspected_file'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:120:in `inspect_files'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/runner.rb:73:in `run'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/rubocop-1.48.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/standard-1.26.0/lib/standard/runners/rubocop.rb:15:in `call'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/standard-1.26.0/lib/standard/cli.rb:14:in `run'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/gems/standard-1.26.0/exe/standardrb:7:in `<top (required)>'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/bin/standardrb:25:in `load'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/bin/standardrb:25:in `<main>'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/bin/ruby_executable_hooks:22:in `eval'
/Users/mikescar/.rvm/gems/ruby-3.2.2@staffing-referrals/bin/ruby_executable_hooks:22:in `<main>'
```

## Steps to reproduce the problem

Add comment beginning with `# appsec: `.

## RuboCop version

```
$ standardrb -V
Standard version: 1.26.0
RuboCop version:  1.48.1 (using Parser 3.2.2.0, rubocop-ast 1.28.0, running on ruby 3.2.2) [arm64-darwin21]
```

**Comment by koic** [comment] 2023-04-17 04:51
Can you provide reproducible example code?

**Comment by koic** [comment] 2023-04-21 03:23
I will close this issue because unknown steps to reproduce. Please feel free to reopen if you can describe a reproduction procedure.

**Closed by koic** 2023-04-21 03:23 UTC

**Comment by mikescar** [comment] 2023-04-21 12:46
sample line: 
`# appsec: this is an appsec-related comment`
