### ISSUE TITLE
Disable the Naming/InclusiveLanguage cop by default

### ISSUE THREAD

**Issue by johnnyshields** [rubocop/rubocop#10069] opened 2021-09-08 03:40 UTC
The `Naming/InclusiveLanguage` cop reflects a preference for politically correct language originating from US that is not universally held. Any cop related to political or religious naming preferences should be opt-in.

(For example, Chinese users might find any variable named `taiwan` or reference to `TW` country code to be offensive.)

**Comment by Drenmi** [comment] 2021-09-08 03:42
Closing as duplicate of #9947.

**Closed by Drenmi** 2021-09-08 03:42 UTC
Labels: duplicate
