### ISSUE TITLE
Alias `add_offense` with `add_match`

### ISSUE THREAD

**Issue by baweaver** [rubocop/rubocop#8134] opened 2020-06-10 17:03 UTC
## Is your feature request related to a problem? Please describe.

With autocorrection in use for code transitions the idea that the starting code is an 'offense' may not be accurate. It may be more accurately phrased as a match of the rule we want to correct for.

These are similar to codemods from EmberJS and a newer idea to Rubocop with autocorrection features:

https://github.com/ember-codemods/ember-test-helpers-codemod

The idea that the starting code is an 'offense' does not feel correct in these circumstances.

## Describe the solution you'd like

An alias for `add_offense`: `add_match`

This would be done to add clarity for code modifications while maintaining support for current rules using `add_offense`.

I can write the code fairly quickly for this but would want to ask the core team about ideas on this in general.

**Comment by bbatsov** [comment] 2020-06-12 06:17
> With autocorrection in use for code transitions the idea that the starting code is an 'offense' may not be accurate. It may be more accurately phrased as a match of the rule we want to correct for.

To some extent you're right. Typically there's some target node pattern and we're looking for a match, but this also updates that `@offenses` array, which I assume lead me to name it like this in the early days (although today I would have probably used `register_offense`). Here's the code of the method:

```ruby
      def add_offense(node, location: :expression, message: nil, severity: nil)
        loc = find_location(node, location)

        return if duplicate_location?(loc)

        severity = find_severity(node, severity)
        message = find_message(node, message)

        status = enabled_line?(loc.line) ? correct(node) : :disabled

        @offenses << Offense.new(severity, loc, message, name, status)
        yield if block_given? && status != :disabled
      end
```

I wouldn't mind an alias that adds more clarity, but I'm not sure whether `add/register_match` won't confuse some people instead.

**Comment by dvandersluis** [comment] 2022-08-04 18:43
@bbatsov are you still considering this?

**Comment by bbatsov** [comment] 2022-08-05 06:06
I had totally forgotten about it. :-) As no one else voiced support for this I guess we are probably fine without an alias, but I'm still open to the idea. It kind of fits the spirit of Ruby (even if I've often criticized its excessive usage of aliases in the Core library). 

If we do this we'll also have to document the use case for which the alias was intended.

**Comment by dvandersluis** [comment] 2022-08-09 14:28
Since there hasn't been a push for it, or really a specific use case, since the original request 2 years ago, I'm going to close this for now. It can be brought back up of course!

**Closed as not planned by dvandersluis** 2022-08-09 14:28 UTC
