### ISSUE TITLE
ENV name variable is incorrectly modified in a RegEx

### ISSUE THREAD

**Issue by jchatel** [rubocop/rubocop#10943] opened 2022-08-21 09:51 UTC
I have a domain contraint in my route

```
  constraints domain: /.*\.ENV['QM_META'][0-9]*\..*/i do
    get '/' => 'next#abuse'
  end
```

Rubocop incorrectly change the name of my Environment variable from `QM_META` to `QM_ETA` and removes the second `'`

```
  constraints domain: /.*\.ENV['QM_ETA][0-9]*\..*/i do
    get '/' => 'next#abuse'
  end
```

--------

## Expected behavior

Environment variable name should not be modified

## Actual behavior

Environment variable 'QM_META` is changed to `QM_ETA`

## Steps to reproduce the problem

Add this to your route file and execute rubocop

```
  constraints domain: /.*\.ENV['QM_META'][0-9]*\..*/i do
    get '/' => 'next#abuse'
  end
```

## RuboCop version

`1.35.0`

****

Changes in my env variable name in my routes from `QM_META` into `QM_ETA` (which does not exist)

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/3944757/185785279-f2267be6-d536-4f48-b85d-867f4f286bfa.png">

**Comment by koic** [comment] 2022-08-21 11:50
This looks like expected behavior. Because the reported regular expression is simplified, it looks like `M` is duplicated in `/['QM_META]/`.
https://ruby-doc.org/core-3.1.2/Regexp.html#class-Regexp-label-Character+Classes

**Comment by jchatel** [comment] 2022-08-21 12:57
I forgot to add the quote in the initial text, you can see it in the github picture. I did not remark one quote was gone too.
It's a string for accessing an env variable, doesn't matter how many M are used, this should not be modified.

**Comment by koic** [comment] 2022-08-21 13:40
`[abc]` is a pattern that represents whether any one enclosed in `[...]` matches. So, it looks like expected behavior with the redundant `'` removed.

The behavior you expect seems to require quoting. WDYT?

```diff
-/.*\.ENV['QM_META'][0-9]*\..*/i
+/.*\.ENV\['QM_META'\][0-9]*\..*/i
```

**Comment by koic** [comment] 2022-08-24 04:35
I'm going close this issue but please let me know if my understanding is wrong. Thank you.

**Closed by koic** 2022-08-24 04:35 UTC
