### ISSUE TITLE
Style/RedundantParentheses comma autocorrect bug

### ISSUE THREAD

**Issue by vlad-pisanov** [rubocop/rubocop#10882] opened 2022-08-08 08:15 UTC
Consider

```ruby
foo(
  (
    1
  ),
  2
)
```

`Style/RedundantParentheses` autocorrects this to the non-parsable:

```ruby
foo(

    1
  ,
  2
)
```

Presumably, the comma should be carried up to the previous line:

```ruby
foo(

    1,
  2
)
```

## RuboCop version

```
1.33.0 (using Parser 3.1.2.0, rubocop-ast 1.19.1, running on ruby 2.6.9 x86_64-darwin21)
  - rubocop-minitest 0.21.0
  - rubocop-performance 1.14.3
  - rubocop-rails 2.15.2
```

**Comment by dvandersluis** [comment] 2022-08-08 16:44
I'm going to close this as a duplicate of #10883 because it's the same fix.

**Closed by dvandersluis** 2022-08-08 16:44 UTC
Labels: bug
