### ISSUE TITLE
`Style/ArgumentsForwarding` unsafe autocorrect example

### ISSUE THREAD

**Issue by Zajn** [rubocop/rubocop#12620] opened 2024-01-15 20:12 UTC
Hi, we updated to `rubocop 1.60.0` today and had several auto-correctable offenses for `Style/ArgumentsForwarding`. Running `bundle exec rubocop --only Style/ArgumentsForwarding -A` yielded updated code that does not do the same thing as it did before auto-correction. 

The corrections that caused issues in our case were examples in which a block was forwarded to another method, along with additional arguments. 

If this is already handled as a configuration option, I apologize for not searching hard enough.

--------

## Expected behavior

```ruby
def use_time_zone(&)
  Time.use_zone(current_identity.time_zone, &)
end
```
This code should either require manual updating, or be corrected to not clobber the non-forwarded arguments (`current_identity.time_zone`, in this case)

## Actual behavior

The above code is auto-corrected to:
```ruby
def use_time_zone(...)
  Time.use_zone(...)
end
```
which does not perform the same.

## Steps to reproduce the problem
Run `bundle exec rubocop --only Style/ArgumentsForwarding -A` on above code

## RuboCop version
```
1.60.0 (using Parser 3.3.0.3, rubocop-ast 1.30.0, running on ruby 3.2.2) [arm64-darwin21]
  - rubocop-performance 1.20.2
  - rubocop-rails 2.23.1
  - rubocop-rspec 2.26.1
```

**Comment by koic** [comment] 2024-01-17 06:02
The issue is caused by the same reason as #12618 and is planned to be resolved in #12624.

**Closed by koic** 2024-01-17 06:02 UTC
Labels: bug
