### ISSUE TITLE
Rubocop Cache not cleared

### ISSUE THREAD

**Issue by Piioo** [rubocop/rubocop#13003] opened 2024-06-18 07:39 UTC
# The Problem
Im using rubocop (1.64.1) in our Rails app, with RSpec and FactoryBot.

In current version we have tried to add `- rubocop-factory_bot` to `require:` in `.rubocop.yml` file.
We have add this gem too in our Gemfile `gem 'rubocop-factory_bot', require: false`.

When we run `rubocop` we get this error:
```
---> rubocop
cannot load such file -- rubocop-factory_bot
/Users/pisz/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load'
```

When I add a breakpoint (binding.pry) into `/Users/pisz/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb` it was not respected and we got the same error. When I remove the file we got the same error.

# Fixed with
The error was only fixed, when I removed the `rubocop_cache` in `/Users/pisz/.cache/`.
https://docs.rubocop.org/rubocop/usage/caching.html#cache-path

# How to reproduce
1. Remove the Cache and remove the additional gem like `rubocop-factory_bot` from Gemfile
2. Run rubocop, which generates the rubocop cache and throws an error
3. Add the gem to the Gemfile back (bundle)
4. Run rubocop -> same error 

## RuboCop version

```
✗ rubocop -V
1.64.1 (using Parser 3.3.3.0, rubocop-ast 1.31.3, running on ruby 3.3.2) +server [arm64-darwin23]
  - rubocop-factory_bot 2.26.1
  - rubocop-rails 2.25.0
  - rubocop-rspec 3.0.1
```

# Additional Info
https://github.com/rubocop/rubocop-factory_bot/issues/128

This does not help
```
AllCops:
  UseCache: false
```

**Comment by Earlopain** [comment] 2024-06-18 08:06
You're using the server mode which doesn't restart/reload in this case. I'd guess this is a duplicate of https://github.com/rubocop/rubocop/issues/12557

**Comment by koic** [comment] 2024-06-18 08:12
Unfortunately, server mode doesn't yet support detecting upgrades or configuration changes. During upgrades, `rubocop --restart-server` is required. For more information, please visit: https://docs.rubocop.org/rubocop/1.64/usage/server.html#restart-server

**Closed by koic** 2024-06-18 08:12 UTC

**Comment by Piioo** [comment] 2024-06-18 08:16
@Earlopain thanks, I tried it out.

With `--no-server` rubocop works like expected.

So `server` option is default.

The problem is, when one developer adds a new `update`, other developers needs to run `restart-server`. Otherwise they will have will get incomprehensible errors....

Thanks

**Comment by Earlopain** [comment] 2024-06-18 08:22
The server is not default, you probably startet it at one point yourself. You can do `--stop-server` and subsequent commands will run without the server.

**Comment by Piioo** [comment] 2024-06-18 08:39
But we have the same issue on our gitlab ci, which starts only with `bundle exec rubocop`

**Comment by Piioo** [comment] 2024-06-18 08:42
I have run the `--stop-server` and then do the same steps to reproduce, -> same error. 

I cant stop the server

**Comment by Earlopain** [comment] 2024-06-18 09:07
You must have some dependency that does this for you. You mentioned you can't reproduce on a fresh rails app.
