### ISSUE TITLE
problem with stringio

### ISSUE THREAD

**Issue by AndreiMotinga** [rubocop/rubocop#13561] opened 2024-12-09 22:44 UTC
Apologies, not sure how to properly report it. 
running neovim setup with rubocop for formatter and some lsp related things and it keeps crashing and replacing file content with this error. 

```
➜  git:(master) rubocop
/Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/socket_reader.rb:36:in `ensure in read!': undefined method `string' for nil:NilClass (NoMethodError)

        Cache.stderr_path.write(stderr.string)
                                      ^^^^^^^
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/socket_reader.rb:37:in `read!'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:90:in `read_socket'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:65:in `block in process_input'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/cache.rb:150:in `write_pid_file'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:64:in `process_input'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:53:in `block in detach_server'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:46:in `fork'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:46:in `detach_server'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:38:in `start'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/start.rb:42:in `block in run'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/cache.rb:137:in `acquire_lock'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/start.rb:29:in `run'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/exec.rb:40:in `ensure_server!'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/exec.rb:19:in `run'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/exe/rubocop:12:in `<top (required)>'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/bin/rubocop:25:in `load'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/bin/rubocop:25:in `<main>'
/Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/socket_reader.rb:27:in `read!': uninitialized constant RuboCop::Server::SocketReader::StringIO (NameError)

        stderr = StringIO.new
                 ^^^^^^^^
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:90:in `read_socket'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:65:in `block in process_input'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/cache.rb:150:in `write_pid_file'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:64:in `process_input'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:53:in `block in detach_server'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:46:in `fork'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:46:in `detach_server'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/core.rb:38:in `start'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/start.rb:42:in `block in run'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/cache.rb:137:in `acquire_lock'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/start.rb:29:in `run'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/exec.rb:40:in `ensure_server!'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/exec.rb:19:in `run'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/exe/rubocop:12:in `<top (required)>'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/bin/rubocop:25:in `load'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/bin/rubocop:25:in `<main>'
bundler: failed to load command: rubocop (/Users/andrei.motinga/.rbenv/versions/3.1.2/bin/rubocop)
/Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/exec.rb:53:in `status': RuboCop server: Could not find status file at: /Users/andrei.motinga/.cache/rubocop_cache/server/Users+andrei.motinga+dev+knowde-web/status (RuntimeError)
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/lib/rubocop/server/client_command/exec.rb:27:in `run'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.65.1/exe/rubocop:12:in `<top (required)>'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/bin/rubocop:25:in `load'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/bin/rubocop:25:in `<top (required)>'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/cli.rb:451:in `exec'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/cli.rb:34:in `dispatch'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/cli.rb:28:in `start'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/exe/bundle:28:in `block in <top (required)>'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.5/exe/bundle:20:in `<top (required)>'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
        from /Users/andrei.motinga/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'

```

**Comment by koic** [comment] 2024-12-10 02:45
This issue may be a duplicate of https://github.com/rubocop/rubocop/issues/13454. Please upgrade RuboCop to the latest version (1.69).

**Closed by koic** 2024-12-10 02:45 UTC
