### ISSUE TITLE
Style/AccessModifierDeclarations does not recognize AllowModifiersOnAttrs/Symbols

### ISSUE THREAD

**Issue by dmke** [rubocop/rubocop#13453] opened 2024-11-13 14:37 UTC
The Style/AccessModifierDeclarations cop seems to be borked.

This issue seem to exist for longer than the last half dozen or so releases. I have checked against RuboCop 1.68.0,  1.67.0, 1.65.0, and 1.0.0.

Given Ruby 3.2, RuboCop 1.68.0 and these files:

<details><summary><code>Gemfile</code></summary>

```rb
source "https://rubygems.org"

gem "rubocop"
```

</details>
<details><summary><code>Gemfile.lock</code></summary>

```
GEM
  remote: https://rubygems.org/
  specs:
    ast (2.4.2)
    json (2.8.1)
    language_server-protocol (3.17.0.3)
    parallel (1.26.3)
    parser (3.3.6.0)
      ast (~> 2.4.1)
      racc
    racc (1.8.1)
    rainbow (3.1.1)
    regexp_parser (2.9.2)
    rubocop (1.68.0)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 2.4, < 3.0)
      rubocop-ast (>= 1.32.2, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.35.0)
      parser (>= 3.3.1.0)
    ruby-progressbar (1.13.0)
    unicode-display_width (2.6.0)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  rubocop

BUNDLED WITH
   2.5.23
```

</details>
<details open><summary><code>test.rb</code></summary>

```rb
class TestAttr
  private attr_reader :foo, :bar
end

class TestSymbol
  private :x, :y
end

class TestBoth
  private attr_reader :foo, :bar
  private :x, :y
end
```

</details>

--------

## Expected behavior

Using the default configuration (i.e. `AllowModifiersOnAttrs: true` and `AllowModifiersOnSymbols: true`), the `test.rb` should not have any `Style/AccessModifierDeclarations` violations.

## Actual behavior

<details open><summary>Output</summary>

```console
$ bundle exec rubocop --debug --only Style/AccessModifierDeclarations test.rb
For /tmp/tmp.zjwOJJC1eK: Default configuration from /tmp/tmp.zjwOJJC1eK/.gems/3.2/gems/rubocop-1.68.0/config/default.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /tmp/tmp.zjwOJJC1eK/test.rb
C

Offenses:

test.rb:2:3: C: [Correctable] Style/AccessModifierDeclarations: private should not be inlined in method definitions.
  private attr_reader :foo, :bar
  ^^^^^^^
test.rb:6:3: C: [Correctable] Style/AccessModifierDeclarations: private should not be inlined in method definitions.
  private :x, :y
  ^^^^^^^
test.rb:11:3: C: [Correctable] Style/AccessModifierDeclarations: private should not be inlined in method definitions.
  private :x, :y
  ^^^^^^^

1 file inspected, 3 offenses detected, 3 offenses autocorrectable
Finished in 0.04921097400074359 seconds
```

Interestingly, in `TestBoth`, the `private attr_reader ...` line is fine.

## Steps to reproduce the problem

- Install RuboCop 1.68.0
- Copy the `test.rb` from above to disk
- Run `rubocop --only Style/AccessModifierDeclarations test.rb`

## RuboCop version

```
$ bundle exec rubocop -V
1.68.0 (using Parser 3.3.6.0, rubocop-ast 1.35.0, analyzing as Ruby 3.2, running on ruby 3.2.5) [x86_64-linux]
```

**Comment by Earlopain** [comment] 2024-11-13 19:15
One part of the issue is already fixed on master, the offenses right now are:

```
test.rb:2:3: C: [Correctable] Style/AccessModifierDeclarations: private should not be inlined in method definitions.
  private attr_reader :foo, :bar
  ^^^^^^^
test.rb:10:3: C: [Correctable] Style/AccessModifierDeclarations: private should not be inlined in method definitions.
  private attr_reader :foo, :bar
  ^^^^^^^
```

So it does not handle these cases yet. The fix is simple I believe (basically the same as https://github.com/rubocop/rubocop/pull/13404) but I will wait until https://github.com/rubocop/rubocop/pull/13443 is merged to make a PR so that autocorrect will not be wrong.

@dvandersluis feel free to pick this up as well if you want, you seem to be familiar with this cop right now already.

**Comment by dvandersluis** [comment] 2024-11-13 19:27
Thanks @Earlopain I'll take a look.

**Comment by dvandersluis** [comment] 2024-11-14 17:54
I opened #13457. With that and the changes in master, I do not get any `Style/AccessModifierDeclarations` offenses with your test code and the default config.

**Comment by dmke** [comment] 2024-11-15 09:39
Thanks, I'll try that later on our production code base and report if I found any remaining issues.

**Comment by dmke** [comment] 2024-11-18 10:03
@dvandersluis, running your PR on our code base did not yield any new issues :+1:

**Closed** 2024-11-19 16:04 UTC
